language: go
go:
  - 1.9.x
  - tip

before_install:
  - go get -u -v github.com/kardianos/govendor
  - govendor sync
  - govendor install +local 

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./pkg

after_success:
  - bash <(curl -s https://codecov.io/bash)
