
version: '3.1'
services:
  go-http-scheduler:
    build: .
    image: ghiltoniel/go-http-scheduler
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=healthcheck
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=healthcheck